# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingcomment',
            name='building_comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.BuildingComment'),
        ),
        migrations.AlterField(
            model_name='buildingpostcommentlike',
            name='building_post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_post_comments', to='comments.BuildingPostComment'),
        ),
        migrations.AlterUniqueTogether(
            name='buildingcommentlike',
            unique_together=set([('building_comment', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='buildingpostcommentlike',
            unique_together=set([('building_post_comment', 'user')]),
        ),
    ]
