# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_building_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='img',
            field=models.ImageField(default=None, upload_to='building/'),
        ),
    ]
