# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_auto_20170921_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='img',
            field=models.ImageField(default=None, upload_to='buildings/'),
        ),
    ]
